### ISSUE TITLE
Parsing error when json attribute is named "required"

### ISSUE THREAD

**Issue by fkostadinov** [browserify/browserify-handbook#18]
Browserify throws an error ("Unexpected token :") when importing a JSON file containing a JSON property named "required". Unfortunately, in JSON schema the property "required" is an official keyword.

Example:

File "foo.json" contains the following JSON code:

<code>{
  "required": []
}
</code>

File "bar.js" requires foo.json:

<code>var foo = require('./foo.json');</code>

In this situation, Browserify fails to parse bar.js with the error message "Unexpected token :".

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one on the https://github.com/browserify/browserify repository if this is still relevant.
