### ISSUE TITLE
Something short and sweet to help repo owners who are publishing to bower but not npm

### ISSUE THREAD

**Issue by dylang** [browserify/browserify-handbook#23]
We frequently find code we want to use which the authors have happily published to `bower`, but they haven't published to `npm`. 

You want to help them. You want to encourage them. You want them to understand why `browserify` is such a great solution and how little work it is to publish to `npm`. 

But you are busy and just move along.

Let's create something short and easy to follow that we can use to help these developers understand and support `Browserify`. 
- [ ] What should it say? 
- [ ] Pictures or diagrams?
- [ ] Helpful links?

**Comment by goto-bus-stop** [comment]
Sorry that nobody got to this in almost 5 years :( I guess it doesn't make sense to add it now that npm is almost everyone's first choice. thanks!
