### ISSUE TITLE
Browserify runs in development environment, not server

### ISSUE THREAD

**Issue by David-Hari** [browserify/browserify-handbook#48]
In the "why concatenate" section (https://github.com/substack/browserify-handbook#why-concatenate), it says:

> Browserify is a build step that runs on the server.

While this may be doable, it is more likely that Browserify will be run during development, when building the app.

**Comment by zenflow** [comment]
Agree. It can run on the server ([browserify-middleware](https://github.com/ForbesLindesay/browserify-middleware) is neat) but usually it's run on a dev machine.
Why not make a PR? Personally I would have started there as it would have been about as much effort as opening this issue was.

**Comment by goto-bus-stop** [comment]
Finally fixed :) thanks!
